FROM debian:trixie
RUN apt update -y 
RUN apt-get --yes install g++ \
	libzstd-dev \
	libmimetic-dev \
	autoconf \
	autoconf-archive \
	pkg-config \
	libboost1.88-all-dev \
	default-libmysqlclient-dev \
	git \
	make

CMD /bin/bash



